### PR TITLE
Added unapproved product backlog

### PR DESCRIPTION
**Pull request by charlesmsy**
Hi team,
Please review and comment on anything that needs to be changed in the product backlog so that we may have an agreed backlog before the client sees it.

### CODE REVIEW

**Review by JoshuaAaron — APPROVED** [review]
Looks good. I viewed it on google docs. I would take out the last feature about star ratings. The client said we wouldn't be doing that anytime soon

**Comment by csuttner** [comment]
Hey Charles - looking to discuss this with you on Slack when you have a minute!

**Review by VBeegle — APPROVED** [review]
Looks good! Thank you Charles

**Review by csuttner — APPROVED** [review]
Approved!

**Comment by charlesmsy** [comment]
Waiting for approval from the client before I merge.

**Pull request merged**
